'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, Search } from '../../../components/icons';
import { ButtonLink, CopyButton } from '../../../components/ui';
import { CONTRACT_ADDRESSES, FROZEN_NETWORK } from '../../../lib/config';

import { DOC_TOPICS } from '../topics';

const nav = DOC_TOPICS;

type Section = { heading: string; paragraphs?: string[]; bullets?: string[]; code?: string };
type Page = { title: string; summary: string; sections: Section[] };

const pages: Record<string, Page> = {
  overview: { title: 'A readable path from claim to consensus', summary: 'Evidra turns semantic fact specifications into canonical on-chain verdicts with evidence policy, provenance, freshness, and history attached.', sections: [{ heading: 'The record', paragraphs: ['A Fact is a protocol record: claim identity, source policy, execution attempt, and resolution history. The public app shows canonical and latest separately because recency is not truth.'] }, { heading: 'Contract truth', paragraphs: ['The Registry is canonical. PostgreSQL and the browser API are projections for search and presentation. Important Fact pages can request a direct chain read and show whether visible data is cached or chain-backed.'] }, { heading: 'Integration note', paragraphs: ['Use /api/v1/facts/:factKey for a normalized read model, then re-check the frozen client when a user needs direct finalized verification.'] }] },
  quickstart: { title: 'Quickstart', summary: 'Read the frozen Studio Dev deployment first; add wallet writes only from a connected user account.', sections: [{ heading: '1. Network', paragraphs: [`Use ${FROZEN_NETWORK.name}, chain ${FROZEN_NETWORK.chainId}, and the frozen RPC.`], code: `const network = { chainId: ${FROZEN_NETWORK.chainId}, rpcUrl: '${FROZEN_NETWORK.rpcUrl}' };` }, { heading: '2. Read a Fact', code: "const response = await fetch('/api/v1/facts/<fact-key>');\nconst { fact, canonical_resolution, latest_resolution } = await response.json();" }, { heading: '3. Write from a wallet', paragraphs: ['Connect a browser wallet, verify chain 61997, and submit the supported user method directly. The backend never signs for a user.'] }, { heading: 'Contract truth', paragraphs: ['A finalized wallet transaction still needs a finalized Fact read before the UI says the protocol operation is complete.'] }, { heading: 'Integration note', paragraphs: ['Persist the transaction ID and reconcile it after reload rather than resubmitting after a timeout.'] }] },
  concepts: { title: 'Core concepts', summary: 'The vocabulary that keeps a Fact verifiable instead of vague.', sections: [{ heading: 'Claim and Fact identity', paragraphs: ['claim_key identifies the semantic claim. fact_key adds policy, schema, and template regime. Do not compute either from display text.'] }, { heading: 'Canonical vs latest', paragraphs: ['Canonical is the Registry current truth head. Latest is the newest committed attempt. An unresolved latest reassessment can coexist with a prior canonical TRUE or FALSE.'] }, { heading: 'Contract truth', paragraphs: ['Never reimplement verdict logic in the UI. Read current and latest resolution IDs from the protocol.'] }, { heading: 'Integration note', paragraphs: ['Evidence prose and reasoning summaries are informational metadata, not a replacement for outcome fields.'] }] },
  'fact-specification': { title: 'Fact specification', summary: 'A precise fact starts with a bounded, human-readable claim.', sections: [{ heading: 'Accepted fields', bullets: ['subject, predicate, and optional object_value define the semantic claim.', 'qualifiers and temporal scope the question.', 'description cannot override template rules or source policy.', 'mutability is IMMUTABLE or MUTABLE_WITH_TTL.'] }, { heading: 'Contract truth', paragraphs: ['Field order and serialization belong to the shared protocol client; the contract remains authoritative.'] }, { heading: 'Integration note', paragraphs: ['Use the Create Fact wizard to review exact values before wallet approval.'] }] },
  'source-policies': { title: 'Source policies', summary: 'Policies state which evidence classes, counts, and cross-checks can satisfy a resolution.', sections: [{ heading: 'Useful fields', bullets: ['allowed_classes and disallowed_classes', 'min_primary_sources', 'min_independent_sources', 'require_cross_check', 'policy_hash'], paragraphs: ['An unresolved result with SOURCE_POLICY_UNSATISFIED is a protocol outcome, not a transport error.'] }, { heading: 'Contract truth', paragraphs: ['Policy versions are immutable historical records. A newer version does not rewrite old requests.'] }, { heading: 'Integration note', paragraphs: ['Render policy requirements as explanation, never as frontend verdict logic.'] }] },
  templates: { title: 'Templates', summary: 'A template binds fact type and resolution instructions to an exact version.', sections: [{ heading: 'Versioned authority', paragraphs: ['Template v1 and v2 are distinct protocol identities. Existing requests keep their template ID, version, and hash. Template instructions govern template-backed requests; user context does not replace them.'] }, { heading: 'Contract truth', paragraphs: ['Display the selected version and hash. Never silently upgrade to latest.'] }, { heading: 'Integration note', paragraphs: ['Template requests use the exact default policy bound to that version.'] }] },
  'evidence-provenance': { title: 'Evidence & provenance', summary: 'A URL is an input to source classification, not an automatic vote.', sections: [{ heading: 'Manifest fields', paragraphs: ['Manifest entries can include URL, source class, origin, fetch status, provenance group, primary flag, independence flag, policy eligibility, and evidence hash.'] }, { heading: 'What the UI should say', bullets: ['Official and primary sources can satisfy primary requirements.', 'Independent counts are grouped by provenance.', 'Derived or copied sources are visibly grouped.', 'Reasoning summaries and evidence prose are informational metadata.'] }, { heading: 'Contract truth', paragraphs: ['Canonical outcome and policy_satisfied come from the committed Resolution.'] }, { heading: 'Integration note', paragraphs: ['Evidence URLs are untrusted metadata. Never iframe or inject their HTML.'] }] },
  freshness: { title: 'Freshness & TTL', summary: 'Freshness answers whether a canonical result is inside its validity regime; it is not confidence.', sections: [{ heading: 'Validity regime', paragraphs: ['Immutable facts use valid_until = 0. Mutable facts expire when the contract current time passes valid_until.'] }, { heading: 'Display rules', bullets: ['Use contract/API freshness semantics, not a permanent client boolean.', 'Do not mark old canonical data fresh because a newer unresolved attempt exists.', 'Show the exact timestamp and human-readable TTL together.'] }, { heading: 'Contract truth', paragraphs: ['Use is_fact_fresh or the normalized API freshness field.'] }, { heading: 'Integration note', paragraphs: ['Refresh mutable facts through the wallet flow; do not mutate cache state from the browser.'] }] },
  reassessment: { title: 'Reassessment', summary: 'Reassessment adds new evidence while preserving resolution history.', sections: [{ heading: 'Purpose', paragraphs: ['Reassessment references an existing Fact and sends supplemental HTTPS URLs. This is not a validator appeal button.'] }, { heading: 'Contract truth', paragraphs: ['A new unresolved attempt may leave a previous canonical TRUE or FALSE in place.'] }, { heading: 'Integration note', paragraphs: ['After finalization, re-read the Fact and keep canonical/latest panels separate.'] }] },
  callbacks: { title: 'Callbacks', summary: 'Callback delivery is a separate state machine from canonical resolution.', sections: [{ heading: 'Delivery states', paragraphs: ['States are NOT_REQUESTED, DISPATCHED, ACKNOWLEDGED, and FAILED_REPORTED. DISPATCHED does not mean acknowledged.'] }, { heading: 'Contract truth', paragraphs: ['Callback success never defines canonical resolution success.'] }, { heading: 'Integration note', paragraphs: ['Consumers deduplicate by callback ID and treat delivery telemetry separately from the verdict.'] }] },
  'transaction-lifecycle': { title: 'Transaction lifecycle', summary: 'Wallet approval, consensus, and finalized protocol state are different moments.', sections: [{ heading: 'The path', paragraphs: ['The app shows preparing, wallet approval, submitted, consensus, decided, finalizing, and finalized. A wallet hash does not mean the Fact is complete.'] }, { heading: 'Recovery', bullets: ['Persist transaction ID, method, account, and chain.', 'On reload, reconcile the existing ID before another submit.', 'A timeout after approval is unknown, not safe to resend.', 'After finalization, re-read request and Fact.'] }, { heading: 'Contract truth', paragraphs: ['Only a finalized successful transaction followed by a finalized state read can support completed protocol copy.'] }, { heading: 'Integration note', paragraphs: ['Use the transaction panel to distinguish wallet submission from durable state.'] }] },
  network: { title: 'Network', summary: 'The product is pinned to one GenLayer deployment.', sections: [{ heading: 'Studio Dev', paragraphs: [`${FROZEN_NETWORK.name} · chain ${FROZEN_NETWORK.chainId}`, `Explorer: ${FROZEN_NETWORK.explorerUrl}`], code: FROZEN_NETWORK.rpcUrl }, { heading: 'Contract truth', paragraphs: ['Only the final V1 Studio Dev deployment is supported by this UI.'] }, { heading: 'Integration note', paragraphs: ['Public environment values are configuration only. No secret is sent to the browser.'] }] },
  contracts: { title: 'Contract addresses', summary: 'The final V1 deployment is explicit and never inferred from an older environment.', sections: [{ heading: 'Frozen addresses', paragraphs: ['Use these Studio Dev addresses on chain 61997.'] }, { heading: 'Contract truth', paragraphs: ['Use shared protocol constants and explorer helpers rather than copying addresses across UI components.'] }, { heading: 'Integration note', paragraphs: ['The page below is the human-readable address registry.'] }] },
  api: { title: 'Backend API', summary: 'Use the normalized read API for projections, pagination, search, and public activity.', sections: [{ heading: 'Routes', paragraphs: ['Common routes include /facts, /facts/:factKey, /resolutions/:resolutionId, /policies, /templates, /activity, and /protocol.'], code: 'GET /api/v1/facts/:factKey\nGET /api/v1/facts/:factKey?source=chain\nGET /api/v1/facts?outcome=TRUE&fresh=true&limit=20' }, { heading: 'Contract truth', paragraphs: ['Responses preserve canonical and latest as separate fields; IDs and timestamps are decimal strings.'] }, { heading: 'Integration note', paragraphs: ['Use direct finalized reads when a cached projection needs verification.'] }] },
  'developer-integration': { title: 'Developer integration', summary: 'Compose reads from the shared protocol package or normalized API. Do not invent protocol truth in app code.', sections: [{ heading: 'Read with the package', code: "import { createProtocolClient, FROZEN_NETWORK } from '@evidra/protocol';\n\nconst protocol = createProtocolClient({ rpcUrl: FROZEN_NETWORK.rpcUrl });\nconst fact = await protocol.registry.getFact(factKey);" }, { heading: 'Contract truth', paragraphs: ['User writes originate from the connected browser wallet. Admin and resolver methods are not product UI operations.'] }, { heading: 'Integration note', paragraphs: ['Use explorer helpers from the shared package and never accept arbitrary explorer domains.'] }] },
  'security-model': { title: 'Security model', summary: 'The app treats wallet, evidence, RPC, and cache boundaries as separate trust zones.', sections: [{ heading: 'Rules', bullets: ['No private key or server signing wallet exists in the frontend.', 'Evidence URLs are untrusted metadata: no iframe, HTML injection, or arbitrary server fetch.', 'Wallet writes require chain 61997 and user approval.', 'Canonical state is chain-derived; cached projections are labeled and rebuildable.'] }, { heading: 'Contract truth', paragraphs: ['Contract URL validation and GenVM web restrictions protect resolver fetches. Browser validation is UX preflight only.'] }, { heading: 'Integration note', paragraphs: ['Validate inputs, escape text, use safe external links, and redact wallet/RPC details from logs.'] }] },
  troubleshooting: { title: 'Troubleshooting', summary: 'Common states and what they mean.', sections: [{ heading: 'Wrong network', paragraphs: ['Switch the wallet to GenLayer Studio Dev, chain 61997.'] }, { heading: 'Fact still pending', paragraphs: ['A finalized parent transaction can be followed by resolver work. Inspect request status and latest attempt.'] }, { heading: 'Unresolved or stale', paragraphs: ['UNRESOLVED is a valid terminal protocol outcome. Stale means the canonical validity window elapsed; historical resolution remains readable.'] }, { heading: 'Integration note', paragraphs: ['Do not resubmit automatically after a network timeout.'] }] },
};

export default function DocsClient({ slug: slugParts = [] }: { slug?: string[] }) {
  const slug = slugParts.join('/') || 'overview'; const current = DOC_TOPICS.find(([key]) => key === slug)?.[0] ?? 'overview'; const page: Page = pages[current] ?? (pages.overview as Page); const [filter, setFilter] = useState(''); const visible = DOC_TOPICS.filter(([, label]) => label.toLowerCase().includes(filter.toLowerCase()));
  return <div className="docs-layout"><aside className="docs-sidebar" aria-label="Documentation navigation"><div className="list-control"><Search size={14} /><input aria-label="Filter documentation" placeholder="Find a topic" value={filter} onChange={(event) => setFilter(event.target.value)} /></div>{visible.map(([key, label]) => <Link className={key === current ? 'active' : ''} key={key} href={`/docs/${key}`}>{label}</Link>)}</aside><select className="docs-mobile-select" aria-label="Documentation topic" value={current} onChange={(event) => { window.location.href = `/docs/${event.target.value}`; }}>{nav.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><article className="docs-content"><span className="eyebrow">Evidra documentation</span><h1>{page.title}</h1><p>{page.summary}</p>{current === 'contracts' && <div className="table-scroll"><table className="detail-table"><thead><tr><th>Contract</th><th>Address</th></tr></thead><tbody>{Object.entries(CONTRACT_ADDRESSES).map(([name, address]) => <tr key={name}><td>{name}</td><td><span className="mono">{address}</span> <CopyButton value={address} /></td></tr>)}</tbody></table></div>}{page.sections.map((section) => <section key={section.heading}><h2 id={section.heading === 'Contract truth' ? 'contract-truth' : section.heading === 'Integration note' ? 'integration' : undefined}>{section.heading}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}{section.code && <Code>{section.code}</Code>}</section>)}<h2 id="next">Next step</h2><ButtonLink href={current === 'fact-specification' || current === 'quickstart' ? '/app/create' : '/app/facts'} variant="secondary">Open the application <ArrowRight size={14} /></ButtonLink></article><aside className="docs-toc" aria-label="On this page"><span className="footer-label">On this page</span><a href="#contract-truth">Contract truth</a><a href="#integration">Integration note</a><a href="#next">Next step</a></aside></div>;
}

function Code({ children }: { children: string }) { return <pre className="docs-code"><code>{children}</code><CopyButton value={children} label="Copy" /></pre>; }
