export const DOC_TOPICS = [
  ['overview', 'Overview'],
  ['quickstart', 'Quickstart'],
  ['concepts', 'Core concepts'],
  ['fact-specification', 'Fact specification'],
  ['source-policies', 'Source policies'],
  ['templates', 'Templates'],
  ['evidence-provenance', 'Evidence & provenance'],
  ['freshness', 'Freshness & TTL'],
  ['reassessment', 'Reassessment'],
  ['callbacks', 'Callbacks'],
  ['transaction-lifecycle', 'Transaction lifecycle'],
  ['network', 'Network'],
  ['contracts', 'Contract addresses'],
  ['api', 'Backend API'],
  ['developer-integration', 'Developer integration'],
  ['security-model', 'Security model'],
  ['troubleshooting', 'Troubleshooting'],
] as const;
